### PR TITLE
The Next Web Replica

### PR DESCRIPTION
**Pull request by ZawadiSumba66**

### CODE REVIEW

**Review by ioilmio — CHANGES_REQUESTED** [review]
# Hello @Goldinium @ZawadiSumba66 👋🏼 
### Nice try on this! 💪🏼 
#### Your project is taking shape, you included all the linters config, and also the readme is ok but improbable;

## Required Changes 🔴 
### Include a description for your PR, this will let the reviewers know what have you worked on

Follow the requirements from Odin and specific from Pathwright, in particular, you are working on a responsive design project so you have to move, display and hide different elements depending on the screen size;
#### Let's fix these:

#### Navigation bar
- On medium screen size TWN logo appears at the leftmost part of the scrren

####  The top 3 articles section
- At the very top is totally absent, include this and deal with responsiveness, as specified, you can always refer to the original page [here](https://thenextweb.com/l) to get an idea of what to do;
 #### Latest news section
- On medium screen size it should align 3 articles per row
#### Latest Funding section
- On medium screen size it should align 3 element per row
#### Categories (Apps, Gear, Tech, etc) section
- On medium screen size it should align 2 boxes per row
#### Latest deals section
- On medium screen size it should align 3 boxes per row
### As you can notice you have to focus on the medium screen size responsiveness, get rid of the hidden overflow, and fix the very first section;

#### Fix all of this and submit for another review;  🍀 
For further info or doubts please contact me on slack @illuminatosalvatore

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [ ] TNW now appears and disappears accordingly but it looks disproportionate
image

- [ ]Project is not looking as original, containers are not aligned, elements are not vertically aligned with each other, titles are not aligned on the same position.
image

- [ ] Tablet view should show only 3 elements and this will maintain until mobile view
image

- [ ] 769px width the website shows a margin to the right on the footer and the navbar
image

- [ ] some sections are missing white space around this will make the project look less messy and uncluttered
image

- [ ] Fix the media queries to match these sizes : desktop bigger than 768px, tablet 768px to 426px and mobile from 425px to less px

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Review by abredi — CHANGES_REQUESTED** [review]
### Status: Require changes 🌳 ♲
Hi @, I am  [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR.  👏👏  I appreciate your hard work in replicating thenextweb.com. Kindly fix the following issues.

[REQUIRED]

Fix the blank space on the right top new.
	Use min-width around 768px for the medium screens
	
| Your Copy | Source |
| :---: | :---: |
|Screen Shot 2020-12-04 at 12 53 10 AM|Screen Shot 2020-12-04 at 1 15 43 AM|

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Review by abredi — CHANGES_REQUESTED** [review]
### Status: Require changes 🌳 ♲
Hi @Goldinium and @ZawadiSumba66, I am  [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR.  👏👏   I appreciate your hard work in replicating thenextweb.com. You already fulfilled most of the requirements, kindly fix the following issues. 

[REQUIRED]

The page shouldn't scroll horizontally on any screen size.
Fix the overflow and horizontal scrolling.

_Click the image to view it in full size._

| Your Copy | Source |
| :---: | :---: |
|Screen Shot 2020-12-04 at 9 28 56 AM|Screen Shot 2020-12-04 at 10 12 21 AM|
|Screen Shot 2020-12-04 at 9 39 52 AM|Screen Shot 2020-12-04 at 10 03 14 AM|


Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Review by abredi — APPROVED** [review]
### Status: Approved 🙌 🎇
Hi @Goldinium and @ZawadiSumba66, I am [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR. Congratulations 🎊 👏, you did very well on this project. 👏👏👏  I appreciate your hard work in replicating thenextweb.com.

Now, you can move ahead.

Please don't forget to merge to master. Good luck with the next projects!

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Pull request merged**
